/* FILTER YOUR DATA BASED ON A CONDITION*/

--RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO 0
SELECT *
FROM customers
WHERE score != 0
--RETRIVE CUSTOMERS FROM GERMANY
SELECT *
FROM customers
WHERE country = 'Germany'