/* FILTER YOUR DATA BASED ON A CONDITION*/
--SYNTAX
SELECT *
FROM TableName
WHERE <condition>

--RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO 0
SELECT *
FROM customers
WHERE score != 0
--RETRIVE CUSTOMERS FROM GERMANY
SELECT *
FROM customers
WHERE country = 'Germany'